name: CI Pipeline

# Quand déclencher le pipeline
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  # Job de test et validation
  test:
    name: Tests et Validation
    runs-on: ubuntu-latest

    steps:
      # Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v4

      # Installer Node.js (adapte selon ton langage)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      # Installer les dépendances
      - name: Install dependencies
        run: npm ci

      # Lancer les tests
      - name: Run tests
        run: npm test

      # Vérifier le code (linting)
      - name: Run linter
        run: npm run lint

      # Vérifier que le build fonctionne
      - name: Build project
        run: npm run build

      # Message de succès
      - name: Success message
        run: echo "✅ Tous les tests sont passés ! Le code est prêt à être mergé."
